# Designated language
language: node_js

# Specify the node version
node_js:
  - lts/*

# Perform builds only on the specified branch
branches:
  only:
    - master

cache:
  yarn: true

before_install:
  - export TZ='Asia/Shanghai'

install:
  - yarn global add hexo-cli
  - yarn install

# The script to execute
script:
  - hexo clean
  - hexo generate
  - hexo deploy